export const hotels = [
  {
    id: 1,
    img: "hotel-1.jpg",
    name: "Hotel",
    country: "Italy",
    rating: "8 Rating",
    iconStar: 4,
    price: "$40",
    distance: "Far far away, behind the word mountains, far from the countries",
  },
  {
    id: 2,
    img: "hotel-2.jpg",
    name: "Hotel",
    country: "Italy",
    rating: "8 Rating",
    iconStar: 4,
    price: "$40",
    distance: "Far far away, behind the word mountains, far from the countries",
  },
  {
    id: 3,
    img: "hotel-3.jpg",
    name: "Hotel",
    country: "Italy",
    rating: "8 Rating",
    iconStar: 4,
    price: "$40",
    distance: "Far far away, behind the word mountains, far from the countries",
  },
  {
    id: 4,
    img: "hotel-4.jpg",
    name: "Hotel",
    country: "Italy",
    rating: "8 Rating",
    iconStar: 4,
    price: "$40",
    distance: "Far far away, behind the word mountains, far from the countries",
  },
];
